### PR TITLE
Move Lyo Store to Github

### PR DESCRIPTION
**Pull request by berezovskyi**
Signed-off-by: Andrew Berezovskyi <andriib@kth.se>

### CODE REVIEW

**Comment by berezovskyi** [comment]
Let's also see how the review process would work for us etc.

**Comment by berezovskyi** [comment]
Breaking changes:

* new package name `o.e.lyo.tools.store -> o.e.lyo.tools.store`
* new artifact id `lyo-store -> store-core`

**Comment by berezovskyi** [comment]
I like the new code quality checker:  https://www.codacy.com/app/berezovskyi/lyo-store/pullRequest?prid=787142

**Comment by berezovskyi** [comment]
Cc @yashskhatri

**Comment by jadelkhoury** [comment]
Is this still waiting for a review?
(I was getting so confortable with Gerrit, and now I have to learn a new one!)

**Comment by jamsden** [comment]
So I guess we review the pull request and just add comments here? We can't put the comments on the changes themselves like in Gerrit? Then how do we indicate our reply to the review? +1 in a comment here?

**Comment by berezovskyi** [comment]
For @jadelkhoury and @jamsden: "Review a Github pull request in 90 seconds!" https://youtu.be/2eB1bIgbnkA

**Comment by berezovskyi** [comment]
Main change is around the package name and the POM file: https://github.com/eclipse/lyo-store/pull/4/files#diff-181fc91e6a1ac0e857e9e87826075679

**Comment by berezovskyi** [comment]
I am merging this as you gave me +1 here and I need to request IP log review.

**Comment by jadelkhoury** [comment]
Useful 90 seconds. Thanks 
So, here we only do +1 (no +2 like in gerrit?)


On a more general comment, are we plannning to move away from eclipse/gerrit altogether for all repositories? I missed out on all these threaded discussions, but would appreciate a summary. 
It would be good if we don't have to deal with 2 systems. 

Jad
Ps. Still out in the woods, but back to civilization soon

**Comment by berezovskyi** [comment]
Yes, +1.

Where did you have the threaded discussions on Gerrit/Bugzilla? This one is actually much better for me to see all the discussion in one thread. Plus email replies to Github mails work perfectly (as opposed to Gerrit).

I would like you to get comfy with GH before moving all repos here. Also would be quite challenging to provide the builds before the change is merged to master. Not that critical, but this Gerrit/Hudson integration will be lost, unfortunately, as I understand.

Have fun away from the civilisation!

**Comment by jadelkhoury** [comment]
>Where did you have the threaded discussions on Gerrit/Bugzilla?

There were many discussions about many things (with andrii, jim & koneksys). One of which I suspected (but I might have misunderstood) was about using github or not. I don't know where all these discussions landed, so was wondering.

**Pull request merged**
